# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  build:
    name: build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '~14.17.1'
          cache: yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set to use npm-publish-action@1.3.8 to publish
        uses: pascalgn/npm-publish-action@1.3.8
        with: # All of theses inputs are optional
          tag_name: 'v%s'
          tag_message: 'v%s'
          create_tag: 'true'
          commit_pattern: "^Release (\\S+)"
          workspace: '.'
          publish_command: 'yarn'
          publish_args: '--non-interactive'
          registry-url: https://registry.npmjs.org/
      - uses: actions/setup-node@v2
        with:
          node-version: '~14.17.1'
          cache: yarn
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
