# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# This workflow will run when we release a package
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get Node.js version
        id: nvm
        run: echo name=NODE_VERSION::$(cat .nvmrc) >> GITHUB_OUTPUT
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install packages
        run: node .yarn/releases/yarn-3.5.1.cjs install --immutable
      - name: Check file types
        run: yarn check:type
      - name: Check files formatting
        run: yarn check:format
      - name: Build project
        run: yarn build
      - name: Check if tests are passing
        run: yarn test
      - name: Publish the release
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
